"Tool catalog for the consulting vertical pack."
from engine.spine.types import ToolSpec, ToolMode, AutonomyTier, ScopeLevel

CONSULTING_TOOLS: list[ToolSpec] = [
    # ── HubSpot ──────────────────────────────────────────────────────────────
    ToolSpec(
        name="hubspot.get_deal",
        inputs={"deal_id": "string"},
        system="hubspot",
        mode=ToolMode.read,
        tier=AutonomyTier.T0,
        scope_required=ScopeLevel.entity,
        reversible=True,
        side_effects=[],
    ),
    ToolSpec(
        name="hubspot.update_deal_stage",
        inputs={"deal_id": "string", "stage": "string"},
        system="hubspot",
        mode=ToolMode.write,
        tier=AutonomyTier.T2,
        scope_required=ScopeLevel.entity,
        reversible=True,
        undo="hubspot.update_deal_stage",
        side_effects=["hubspot_deal_updated"],
    ),
    # ── Gmail ────────────────────────────────────────────────────────────────
    ToolSpec(
        name="gmail.get_thread",
        inputs={"thread_id": "string"},
        system="gmail",
        mode=ToolMode.read,
        tier=AutonomyTier.T0,
        scope_required=ScopeLevel.entity,
        reversible=True,
        side_effects=[],
    ),
    ToolSpec(
        name="gmail.send_email",
        inputs={"to": "string", "subject": "string", "body": "string"},
        system="gmail",
        mode=ToolMode.write,
        tier=AutonomyTier.T3,
        scope_required=ScopeLevel.entity,
        reversible=False,
        side_effects=["email_sent"],
    ),
    # ── Calendar ─────────────────────────────────────────────────────────────
    ToolSpec(
        name="calendar.get_events",
        inputs={"date_range": "string", "attendee_ref": "string"},
        system="calendar",
        mode=ToolMode.read,
        tier=AutonomyTier.T0,
        scope_required=ScopeLevel.entity,
        reversible=True,
        side_effects=[],
    ),
    # ── Asana ────────────────────────────────────────────────────────────────
    ToolSpec(
        name="asana.get_project_status",
        inputs={"project_id": "string"},
        system="asana",
        mode=ToolMode.read,
        tier=AutonomyTier.T0,
        scope_required=ScopeLevel.entity,
        reversible=True,
        side_effects=[],
    ),
    ToolSpec(
        name="asana.create_task",
        inputs={"project_id": "string", "title": "string", "due_on": "string"},
        system="asana",
        mode=ToolMode.write,
        tier=AutonomyTier.T2,
        scope_required=ScopeLevel.entity,
        reversible=True,
        undo="asana.delete_task",
        side_effects=["asana_task_created"],
    ),
    # ── QuickBooks ───────────────────────────────────────────────────────────
    ToolSpec(
        name="quickbooks.get_invoice",
        inputs={"invoice_id": "string"},
        system="quickbooks",
        mode=ToolMode.read,
        tier=AutonomyTier.T0,
        scope_required=ScopeLevel.org,
        reversible=True,
        side_effects=[],
    ),
    ToolSpec(
        name="quickbooks.create_invoice",
        inputs={"client_ref": "string", "line_items": "array", "due_date": "string"},
        system="quickbooks",
        mode=ToolMode.write,
        tier=AutonomyTier.T3,
        scope_required=ScopeLevel.org,
        reversible=False,
        side_effects=["invoice_created"],
    ),
    # ── Harvest ──────────────────────────────────────────────────────────────
    ToolSpec(
        name="harvest.get_budget_status",
        inputs={"engagement_ref": "string"},
        system="harvest",
        mode=ToolMode.read,
        tier=AutonomyTier.T0,
        scope_required=ScopeLevel.entity,
        reversible=True,
        side_effects=[],
    ),
    # ── Slack ────────────────────────────────────────────────────────────────
    ToolSpec(
        name="slack.post_message",
        inputs={"channel": "string", "text": "string"},
        system="slack",
        mode=ToolMode.write,
        tier=AutonomyTier.T2,
        scope_required=ScopeLevel.org,
        reversible=False,
        side_effects=["slack_message_sent"],
    ),
]
